name: Specs
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  run-rspec:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Ruby and install gems
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1
          bundler-cache: true
      - name: Install gems with Appraisal
        run: bundle exec appraisal install
      - name: Run RSpec
        run: bundle exec appraisal rspec
